name: Release
on:
  workflow_dispatch:
env:
  BASE_BRANCH: ${{ github.base_ref }}
jobs:
  main: 
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: "read"
      actions: "read"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: | 
          npm ci 
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4
      - name: Get branch name
        id: branch_name
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        run: npx nx affected -t build container
      
          
